---

- hosts: all
  become: yes
  tasks:
    - name: upgrade all yum packages for ansible
      yum:
        name: "*"
        state: latest

    - name: Enable amazon-linux-extras packages
       shell: "amazon-linux-extras enable nginx1.12"

    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes