---

- hosts: all
  become: yes
  tasks:
    - name: upgrade all yum packages for ansible
      yum:
        name: "*"
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes