name: Deploy code to EBS

on:
  push:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy code to EBS
        shell: bash
        working-directory: terraform
        env:
          access_key: ${{ secrets.ACCESS_TOKEN }}
          secret_key: ${{ secrets.SECRET_KEY }}
          s3_bucket: ${{ secrets.BUCKET_NAME }}
        run: |
          export NAME = $(< app-version.txt) 
          aws configure set aws_access_key_id $access_key
          aws configure set aws_secret_access_key $secret_key 
          aws --region us-east-1 elasticbeanstalk update-environment --environment-name fortune-cookie-env --version-label $NAME
 